version: '3'

services:
  postgres-data:
    images:postgres:latest
  volumes:
    - postgres_data:/var/lib/postgresql/data/data/
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=musala-drones
  ports:
    - 5432:5432

volumes:
  postgres_data: